_format_version: "1.1"
services:
- name: tkeir-search-svc
  host: tkeir-search-svc
  port: 9000
  protocol: https
  routes:
  - name: tkeir-search-svc
    paths:
    - /search/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-index-svc
  host: tkeir-index-svc
  port: 10012
  protocol: https
  routes:
  - name: tkeir-index-svc
    paths:
    - /index/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-converter-svc
  host: tkeir-converter-svc
  port: 10000
  protocol: https
  routes:
  - name: tkeir-converter-svc
    paths:
    - /converter/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-tokenizer-svc
  host: tkeir-tokenizer-svc
  port: 10001
  protocol: https
  routes:
  - name: tkeir-tokenizer-svc
    paths:
    - /tokenizer/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-mstagger-svc
  host: tkeir-mstagger-svc
  port: 10002
  protocol: https
  routes:
  - name: tkeir-mstagger-svc
    paths:
    - /mstagger/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-nertagger-svc
  host: tkeir-nertagger-svc
  port: 10003
  protocol: https
  routes:
  - name: tkeir-nertagger-svc
    paths:
    - /nertagger/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-syntax-svc
  host: tkeir-syntax-svc
  port: 10004
  protocol: https
  routes:
  - name: tkeir-syntax-svc
    paths:
    - /syntax/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-keywords-svc
  host: tkeir-keywords-svc
  port: 10007
  protocol: https
  routes:
  - name: tkeir-keywords-svc
    paths:
    - /keywords/1.0
    strip_path: true
    plugins:
    - name: key-auth
  

- name: tkeir-clusterinfer-svc
  host: tkeir-clusterinfer-svc
  port: 10013
  protocol: https
  routes:
  - name: tkeir-clusterinfer-svc   
    paths:
    - /clusterinfer/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-embeddings-svc
  host: tkeir-embeddings-svc
  port: 10005
  protocol: https
  routes:
  - name: tkeir-embeddings-svc
    paths:
    - /embeddings/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-summarizer-svc
  host: tkeir-summarizer-svc
  port: 10008
  protocol: https
  routes:
  - name: tkeir-summarizer-svc
    paths:
    - /summarizer/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-sentiment-svc
  host: tkeir-sentiment-svc
  port: 10009
  protocol: https
  routes:
  - name: tkeir-sentiment-svc
    paths:
    - /sentiment/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-classifier-svc
  host: tkeir-classifier-svc
  port: 10010
  protocol: https
  routes:
  - name: tkeir-classifier-svc
    paths:
    - /classifier/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-qa-svc
  host: tkeir-qa-svc
  port: 10011
  protocol: https
  routes:
  - name: tkeir-qa-svc
    paths:
    - /qa/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-pipeline-svc
  host: tkeir-pipeline-svc
  port: 10006
  protocol: https
  routes:
  - name: tkeir-pipeline-svc
    paths:
    - /pipeline/1.0
    strip_path: true
    plugins:
    - name: key-auth

- name: tkeir-shell
  host: tkeir-shell
  port: 10006
  protocol: https
  routes:
  - name: tkeir-pipeline-shell-svc
    paths:
    - /pipeline-shell/1.0
    strip_path: true
    plugins:
    - name: key-auth

plugins:
 - name: rate-limiting
   config:
     minute: 60
     policy: local
 - name: proxy-cache
   config:
     content_type:
     - "application/json; charset=utf-8"
     cache_ttl: 30
     strategy: memory
 - name: correlation-id
   config: 
     header_name: Kong-Tkeir-Request-ID
     generator: uuid#counter
     echo_downstream: false
consumers:
 - custom_id: <MY CUSTOM ID>
   username: <MY CUSTOM USERNAME>
   keyauth_credentials:
   - key: <CHANGE-ME>
